### ISSUE TITLE
make -j8 does not complete in Mac OS 10.10.5; CLANG 7

### ISSUE THREAD

**Issue by glihm** [NVlabs/nvbio#10]
Hi there, 

I did not complete the installation of nvbio on Mac OS. 
The _cmake_ command ends with one warning about **Policy CMP0042**.
**
-- Generating done
-- Build files have been written to: /Users/wocka/Documents/NV/nvbio/build
**

However, the **make -j8** command generates lot's of error and finished with:
**
[ 39%] Built target htslib
CMake Error at nvbio_generated_sufsort_priv.cu.o.cmake:266 (message):
  Error generating file
  /Users/wocka/Documents/NV/nvbio/build/nvbio/CMakeFiles/nvbio.dir/sufsort/./nvbio_generated_sufsort_priv.cu.o

make[2]: **\*  [nvbio/CMakeFiles/nvbio.dir/sufsort/nvbio_generated_sufsort_priv.cu.o] Error 1
5 errors detected in the compilation of "/tmp/tmpxft_00004075_00000000-6_file_bwt.cpp1.ii".
CMake Error at nvbio_generated_file_bwt.cu.o.cmake:266 (message):
  Error generating file
  /Users/wocka/Documents/NV/nvbio/build/nvbio/CMakeFiles/nvbio.dir/sufsort/./nvbio_generated_file_bwt.cu.o

make[2]: **\* [nvbio/CMakeFiles/nvbio.dir/sufsort/nvbio_generated_file_bwt.cu.o] Error 1
make[1]: **\* [nvbio/CMakeFiles/nvbio.dir/all] Error 2
make: **\* [all] Error 2
**

Thank you for your time to read this issue.

**Comment by nsubtil** [comment]
Mac OS X is not officially supported, though a little effort has been put in the past on making sure nvbio builds on macs. It wouldn't surprise me if it doesn't build right now, you may have to help us fix it :)

You didn't actually paste the compiler error messages, so it's hard to tell what's going on. Note that nvbio is known to only build with CUDA 6.5 and not with more recent versions, so that would be the first thing I'd suggest checking.

**Comment by wocka** [comment]
Thank you for this answer, and sorry for that, I did not see this point: Mac OS X not supported. 

I will work on it! :) 

I am working with CUDA 6.0, I'll upgrade it to CUDA 6.5 and then try it again from scratch and inform you of what happens.
