### ISSUE TITLE
Upload testing files somewhere

### ISSUE THREAD

**Issue by r-barnes** [NVlabs/nvbio#25]
Running `./nvbio-test/nvbio-test` gives the following errors:

    warning : unable to open bwt "./data/human.NCBI36/Human.NCBI36.bwt"
    error   :     failed opening file "./data/SRR493095_1.fastq.gz"

These files were likely too large to include in the repo directory, but prevent the test suite from completing. Is there a way to get them uploaded somewhere?

**Comment by rdwrt** [comment]
Here's the fastq: https://www.ncbi.nlm.nih.gov/sra/SRX145461

**Comment by foertter** [comment]
Added documentation to README. Thanks!

**Comment by r-barnes** [comment]
@rdwrt: I wasn't able to get that file to work. Do you have a more specific link (this one brings you to a webpage from which there seem to be several files)?

**Comment by jpantaleoni** [comment]
you have to first build the .bwt from either a single fasta file or the
complete list chromosomes, using nvBWT:
https://nvlabs.github.io/nvbio/nvbwt_page.html

A single file for hg18 can be found here:
ftp://genome-ftp.cse.ucsc.edu/goldenPath/hg18/bigZips/hg18.2bit

You have to use a utility twoBitToFa to convert it to fasta (though maybe
we have also added support for reading directly from it, I don't recall).

Alternatively, you can find all chromosomes for hg18 here:
http://hgdownload.cse.ucsc.edu/goldenpath/hg18/chromosomes/

Or you could use the top-level assembly for hg19 here:
ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/

But I'd go for the .2bit file first, easiest and less error prone since
it's already assembled.
